import { createBrowserRouter, RouterProvider, NavLink, Outlet, useLocation, useNavigate } from 'react-router'
import { LeagueProvider, useLeague } from './store'
import { Dashboard, Standings, PlayerStatistics, PublishedResults, LeagueSetup, Teams } from './pages'
import { ScoreEntry } from './scores'
import { LayoutDashboard, SlidersHorizontal, Users, ClipboardList, Trophy, ChartNoAxesCombined, Globe, ChevronDown, CalendarDays, CircleHelp, ArrowUpRight, CircleDot, Button, Badge, Menu } from './LeagueKit'
import { useState } from 'react'

const navigation = [{ to: '/', name: 'Dashboard', icon: LayoutDashboard }, { to: '/scores', name: 'Score entry', icon: ClipboardList }, { to: '/teams', name: 'Teams & bowlers', icon: Users }, { to: '/standings', name: 'Standings', icon: Trophy }, { to: '/statistics', name: 'Player statistics', icon: ChartNoAxesCombined }, { to: '/results', name: 'Published results', icon: Globe }]
function Shell() {
  const { state } = useLeague(); const location = useLocation(); const navigate = useNavigate(); const [menu, setMenu] = useState(false); const [help, setHelp] = useState(false)
  const name = navigation.find(item => item.to === location.pathname)?.name || 'League setup'
  return <div className="app-shell"><aside className={`sidebar ${menu ? 'sidebar-open' : ''}`}><NavLink to="/" className="brand"><span className="brand-icon"><CircleDot size={25} strokeWidth={2.5} /></span>lanedesk<span className="brand-period">.</span></NavLink><div className="league-switch"><span className="league-avatar">TN</span><div><strong>{state.league.name}</strong><small>2025 – 2026 season</small></div><ChevronDown size={15} /></div><p className="nav-label">LEAGUE WORKSPACE</p><nav>{navigation.map(({ to, name, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'} onClick={() => setMenu(false)} className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}><Icon size={18} /><span>{name}</span>{to === '/scores' && <span className="nav-count">{state.week}</span>}</NavLink>)}<div className="nav-divider" /><NavLink to="/setup" className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}><SlidersHorizontal size={18} />League setup</NavLink></nav><div className="sidebar-bottom"><div className="season-progress"><div><span>Season progress</span><strong>{Math.min(state.week - 1, 32)} / 32 weeks</strong></div><progress value={state.week - 1} max={32} /><small>One week at a time. Every pin counts.</small></div><Button variant="ghost" className="help-button" onClick={() => setHelp(!help)}><CircleHelp size={18} />Help & getting started<ArrowUpRight size={15} /></Button>{help && <div className="help-note">Set up your league, add your roster, then enter all four matches. Save drafts anytime. Finalizing a week updates standings and statistics.</div>}<div className="user-profile"><span className="user-avatar">JD</span><div><strong>Jamie Davis</strong><small>League secretary</small></div><Badge tone="green">Admin</Badge></div></div></aside><div className="workspace"><header className="topbar"><div className="breadcrumb"><Button variant="ghost" className="menu-button" onClick={() => setMenu(!menu)} aria-label="Toggle navigation"><Menu size={20} /></Button><span>Workspace</span><span className="breadcrumb-slash">/</span><strong>{name}</strong></div><div className="topbar-right"><span className="season-label"><CalendarDays size={15} />2025 – 2026 season</span><span className="topbar-divider" /><Button variant="ghost" onClick={() => navigate('/public')}><Globe size={15} />Public league page<ArrowUpRight size={14} /></Button></div></header><main className="main"><Outlet /></main><footer className="app-footer"><span>Made for the people who keep the league rolling.</span><span>All times local · Data saved in this browser</span></footer></div></div>
}
const router = createBrowserRouter([{ Component: Shell, children: [{ index: true, Component: Dashboard }, { path: 'scores', Component: ScoreEntry }, { path: 'teams', Component: Teams }, { path: 'standings', Component: Standings }, { path: 'statistics', Component: PlayerStatistics }, { path: 'setup', Component: LeagueSetup }, { path: 'results', Component: PublishedResults }] }, { path: 'public', element: <PublishedResults publicView /> }, { path: '*', element: <div className="not-found"><h1>Page not found</h1><NavLink to="/">Return to your dashboard</NavLink></div> }])
export default function App() { return <LeagueProvider><RouterProvider router={router} /></LeagueProvider> }
